### ISSUE TITLE
NPE in cache

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Citadel#10]
[14:15:37 WARN]: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
[14:15:37 WARN]:        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
[14:15:37 WARN]:        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[14:15:37 WARN]:        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[14:15:37 WARN]:        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:99)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.ReinforcementManager.isReinforced(ReinforcementManager.java:149)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.ReinforcementManager.isReinforced(ReinforcementManager.java:160)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.Utility.getRealBlock(Utility.java:641)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.listener.BlockListener.interact(BlockListener.java:396)
[14:15:37 WARN]:        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
[14:15:37 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:15:37 WARN]:        at java.lang.reflect.Method.invoke(Method.java:606)
[14:15:37 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[14:15:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:15:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[14:15:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[14:15:37 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFact
ory.java:228)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[14:15:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[14:15:37 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[14:15:37 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[14:15:37 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:15:37 WARN]: Caused by: java.lang.NullPointerException
[14:15:37 WARN]:        at vg.civcraft.mc.namelayer.permission.GroupPermission.loadPermsforGroup(GroupPermission.java:24
)
[14:15:37 WARN]:        at vg.civcraft.mc.namelayer.permission.GroupPermission.<init>(GroupPermission.java:20)
[14:15:37 WARN]:        at vg.civcraft.mc.namelayer.permission.PermissionHandler.getGroupPermission(PermissionHandler.ja
va:18)
[14:15:37 WARN]:        at vg.civcraft.mc.namelayer.GroupManager.getPermissionforGroup(GroupManager.java:187)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.reinforcement.PlayerReinforcement.<init>(PlayerReinforcement.java:34)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.database.CitadelReinforcementData.getReinforcement(CitadelReinforcemen
tData.java:370)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.ReinforcementManager$2.load(ReinforcementManager.java:47)
[14:15:37 WARN]:        at vg.civcraft.mc.citadel.ReinforcementManager$2.load(ReinforcementManager.java:45)
[14:15:37 WARN]:        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[14:15:37 WARN]:        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[14:15:37 WARN]:        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[14:15:37 WARN]:        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[14:15:37 WARN]:        ... 29 more

Getting this periodically

**Comment by ProgrammerDan** [comment]
Should be addressed in holistic updates to Civcraft mainstream.
