### ISSUE TITLE
Placing a bed with lore causes an exception

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Citadel#19]
```
[08:28:18 WARN]: [Citadel] Utility isDroppedReinforcementBlock failed
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.This world is unforgiving.
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_102]
        at org.bukkit.Material.valueOf(Material.java:1) ~[spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at vg.civcraft.mc.citadel.Utility.isDroppedReinforcementBlock(Utility.java:794) [Citadel-3.6.2.jar:?]
        at vg.civcraft.mc.citadel.listener.BlockListener.onFortificationMode(BlockListener.java:102) [Citadel-3.6.2.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callBlockMultiPlaceEvent(CraftEventFactory.java:119) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.ItemStack.placeItem(ItemStack.java:160) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:534) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:910) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-570526c-75a8885]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by ProgrammerDan** [comment]
Fixed in recent commit.
