### ISSUE TITLE
Error: Could not start chunk meta data, manager was null

### ISSUE THREAD

**Issue by Roadcrosser** [DevotedMC/Citadel#71]
I grabbed Citadel 4.1.1 off the CI for MC 1.16.5 (I hope I got the right version) and got this error:

```
[Citadel] Could not start chunk meta data, manager was null
[Citadel] Errors setting up chunk metadata API, shutting down
```

This was after I uncommented the database lines in the Citadel config that point to the namelayer database (I did try making a seperate database for citadel at some point, though I think that was a mistake so I undid that).

(I'm also using MariaDB instead, if that's relevant)

Leaving those lines commented produces an error about migrations, I'll post the exact error for that if that's relevant.

Full log is here:
```
System Info: Java 14 (OpenJDK 64-Bit Server VM 14.0.1+7) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[19:07:38 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:07:38 INFO]: Reloading ResourceManager: Default, bukkit
[19:07:39 INFO]: Loaded 7 recipes
[19:07:40 INFO]: Starting minecraft server version 1.16.5
[19:07:40 INFO]: Loading properties
[19:07:40 INFO]: This server is running Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[19:07:40 INFO]: Debug logging is disabled
[19:07:40 INFO]: Server Ping Player Sample Count: 12
[19:07:40 INFO]: Using 4 threads for Netty based IO
[19:07:40 INFO]: Default game type: SURVIVAL
[19:07:40 INFO]: Generating keypair
[19:07:40 INFO]: Starting Minecraft server on *:25565
[19:07:40 INFO]: Using default channel type
[19:07:41 INFO]: [CivModCore] Loading CivModCore v1.8.2
[19:07:41 INFO]: [NameLayer] Loading NameLayer v2.14.1
[19:07:41 INFO]: [Citadel] Loading Citadel v4.1.1
[19:07:41 INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:07:41 INFO]: Preparing level "world"
[19:07:41 INFO]: Preparing start region for dimension minecraft:overworld
[19:07:41 INFO]: Loaded 0 spawn chunks for world world
[19:07:41 INFO]: Preparing spawn area: 0%
[19:07:41 INFO]: Time elapsed: 383 ms
[19:07:41 INFO]: Preparing start region for dimension minecraft:the_nether
[19:07:41 INFO]: Loaded 0 spawn chunks for world world_nether
[19:07:42 INFO]: Preparing spawn area: 0%
[19:07:42 INFO]: Time elapsed: 243 ms
[19:07:42 INFO]: Preparing start region for dimension minecraft:the_end
[19:07:42 INFO]: Loaded 0 spawn chunks for world world_the_end
[19:07:42 INFO]: Time elapsed: 70 ms
[19:07:42 INFO]: [CivModCore] Enabling CivModCore v1.8.2
[19:07:42 INFO]: [CivModCore] Command [ConfigCommand] registered.
[19:07:42 INFO]: [CivModCore] Command [ChunkOperationManager] registered.
[19:07:42 INFO]: [CivModCore] [EnchantUtils] Loaded a total of 38 abbreviations from enchants.yml
[19:07:42 INFO]: [CivModCore] [ItemUtils] Loaded a total of 1076 item names from materials.yml
[19:07:42 WARN]: [CivModCore] [ItemUtils] The following materials are missing from materials.yml: PIGLIN_BRUTE_SPAWN_EGG.
[19:07:42 WARN]: [MoreTags] The following crops are missing: TWISTING_VINES,WEEPING_VINES.
[19:07:42 WARN]: [SpawnEggUtils] The following spawn eggs are missing: PIGLIN_BRUTE_SPAWN_EGG.
[19:07:42 INFO]: [NameLayer] Enabling NameLayer v2.14.1
[19:07:42 INFO]: Connecting to namelayer@localhost:3306 using mc_namelayer
[19:07:42 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[19:07:43 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[19:07:43 INFO]: Successfully connected to the database.
[19:07:43 INFO]: [NameLayer:] Info follows
Welcome back, oldtimer.
[19:07:43 INFO]: [NameLayer:] Info follows
Removing any cycles...
[19:07:43 INFO]: [NameLayer] Removed 0 subgroup cycles
[19:07:43 INFO]: [NameLayer] Update prepared, starting database update.
[19:07:43 INFO]: Lock acquired, proceeding.
[19:07:43 INFO]: NameLayer database is up to date.
[19:07:43 INFO]: Lock released.
[19:07:43 INFO]: [NameLayer] Database update took 0 seconds
[19:07:43 INFO]: [Citadel] Enabling Citadel v4.1.1
[19:07:43 WARN]: [CivModCore] Loaded class vg.civcraft.mc.citadel.command.PatchMode from Citadel v4.1.1 which is not a depend, softdepend or loadbefore of this plugin.
[19:07:43 INFO]: [Citadel] Parsing config.
[19:07:43 INFO]: Connecting to namelayer@localhost:3306 using mc_namelayer
[19:07:43 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Starting...
[19:07:43 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Start completed.
[19:07:43 INFO]: Successfully connected to the database.
[19:07:43 INFO]: [Citadel] Debug mode: enabled
[19:07:43 INFO]: [Citadel] Logging replies: disabled
[19:07:43 INFO]: [Citadel] Adding GOLD_BLOCK as valid acid material
[19:07:43 INFO]: [Citadel] Parsed reinforcement type Stone for item ItemStack{STONE x 1}, returnChance: 1.0, maturationTime: 5 min, acidTime: 20 min, gracePeriod: 0, id: 1
[19:07:43 INFO]: [Citadel] Parsed reinforcement type Iron for item ItemStack{IRON_INGOT x 1}, returnChance: 1.0, maturationTime: 30 min, acidTime: 6 h, gracePeriod: 0, id: 2
[19:07:43 INFO]: [Citadel] Parsed reinforcement type Diamond for item ItemStack{DIAMOND x 1}, returnChance: 1.0, maturationTime: 4 h, acidTime: 48 h, gracePeriod: 0, id: 3
[19:07:43 INFO]: [Citadel] Parsed reinforcement type Bedrock for item ItemStack{BEDROCK x 1}, returnChance: 1.0, maturationTime: 1 sec, acidTime: 1 sec, gracePeriod: 0, id: 4
[19:07:43 INFO]: [Citadel] Config parsed.
[19:07:43 INFO]: Lock acquired, proceeding.
[19:07:43 INFO]: Citadel database is up to date.
[19:07:43 INFO]: Lock released.
[19:07:43 ERROR]: [Citadel] Could not start chunk meta data, manager was null
[19:07:43 ERROR]: [Citadel] Errors setting up chunk metadata API, shutting down
[19:07:43 INFO]: Running delayed init tasks
[19:07:43 INFO]: Done (3.229s)! For help, type "help"
[19:07:43 INFO]: Stopping server
[19:07:43 INFO]: [Citadel] Disabling Citadel v4.1.1
[19:07:43 ERROR]: Error occurred while disabling Citadel v4.1.1 (Is it up to date?)
java.lang.NullPointerException: null
        at vg.civcraft.mc.citadel.Citadel.onDisable(Citadel.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:435) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:770) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:704) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1044) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
        at java.lang.Thread.run(Unknown Source) [?:?]
[19:07:43 INFO]: [NameLayer] [MojangNames] Mojang profiles loaded!
[19:07:43 INFO]: [NameLayer] Disabling NameLayer v2.14.1
[19:07:43 INFO]: [CivModCore] Disabling CivModCore v1.8.2
[19:07:43 INFO]: [NBTSerialization] All NBTSerialization registered classes have been cleared.
[19:07:43 INFO]: Saving players
[19:07:43 INFO]: Saving worlds
[19:07:43 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[19:07:47 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[19:07:47 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[19:07:49 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:07:49 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[19:07:50 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:07:50 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[19:07:50 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:07:50 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:07:50 INFO]: Flushing Chunk IO
> [19:07:50 INFO]: Closing Thread Pool
[19:07:50 INFO]: Closing Server
```

**Comment by Roadcrosser** [comment]
I also found this same error in the #69 issue, so I'm unsure if my version is actually outdated.

**Comment by Roadcrosser** [comment]
Digging through the code, it looks like this error came about because the CivModCore database config was commented out, despite the config itself saying uncommenting it was a bad idea. I wonder if I'm doing something wrong here.

I populated the db info with my namelayer db and it seems to work fine now.

Should I have seperate dbs for CivModCore, Namelayer and Citadel or can they all be the same db?

**Comment by ProgrammerDan** [comment]
As far as I know they can be either same or separate DBs, but I do not have
the most recent knowledge of changes made.
